#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "digest"
require "optparse"
require "pathname"
require "rbconfig"
require "set"
require_relative "../lib/architecture_verifier"
require_relative "../lib/strict_yaml"

module PagesBuild
  ROOT = File.expand_path("..", __dir__)
  DEFAULT_OUTPUT = File.join(ROOT, "dist")
  OUTPUT_MARKER_SUFFIX = ".explainer-pages-output"
  LEGACY_OUTPUT_MARKER = ".explainer-pages-output"
  REFERENCE_PANEL_ASSET = %r{\Aassets/reference-panels/[a-z0-9][a-z0-9_/-]*\.(?:png|jpe?g|webp)\z}.freeze

  ROOT_ASSETS = %w[
    index.html
    landing.js
    styles.css
    theme-init.js
    theme-state.mjs
  ].freeze

  RENDERER_ASSETS = %w[
    renderer/architecture/board-surface.mjs
    renderer/architecture/comparison-board-renderer.mjs
    renderer/architecture/comparison-state.mjs
    renderer/architecture/content-grid.mjs
    renderer/architecture/deep-link-state.mjs
    renderer/architecture/edge-annotations.mjs
    renderer/architecture/flow-families.mjs
    renderer/architecture/index.html
    renderer/architecture/keyboard-navigation.mjs
    renderer/architecture/math-notation.mjs
    renderer/architecture/orthogonal-routing.mjs
    renderer/architecture/question-context.mjs
    renderer/architecture/renderer-model.mjs
    renderer/architecture/renderer.js
    renderer/architecture/repeat-regions.mjs
    renderer/architecture/representation-glyphs.mjs
    renderer/architecture/semantic-pseudocode.mjs
    renderer/architecture/semantic-routing.mjs
    renderer/architecture/visual-segments.mjs
    renderer/architecture/workspace-selection.mjs
  ].freeze

  GENERATED_ASSETS = {
    "_headers" => <<~HEADERS,
      /*
        Cache-Control: no-cache, must-revalidate
        X-Content-Type-Options: nosniff
        Referrer-Policy: strict-origin-when-cross-origin
        X-Frame-Options: SAMEORIGIN
    HEADERS
  }.freeze

  class Error < StandardError; end

  module_function

  def registry
    @registry ||= StrictYaml.load_file(File.join(ROOT, "architectures/index.yaml"))
  end

  def source_set_ids
    Array(registry["source_sets"]).map { |source_set| source_set.fetch("id") }
  end

  def resolve_source_set_ids(requested)
    return source_set_ids if requested.nil? || requested.empty?

    selected = requested.map(&:to_s).uniq
    unknown = selected - source_set_ids
    unless unknown.empty?
      raise Error, "unknown source set#{unknown.length == 1 ? '' : 's'}: #{unknown.join(', ')}"
    end
    source_set_ids.select { |id| selected.include?(id) }
  end

  def compiled_assets(selected_source_set_ids)
    [
      "renderer/architecture/manifest-index.js",
      *selected_source_set_ids.map { |id| "renderer/architecture/manifest-#{id}.js" },
    ]
  end

  def reference_panel_assets(selected_source_set_ids = source_set_ids)
    selected = selected_source_set_ids.to_set
    Array(registry["source_sets"]).filter_map do |source_set|
      source_set if selected.include?(source_set.fetch("id"))
    end.flat_map do |source_set|
      view = StrictYaml.load_file(File.join(ROOT, source_set.fetch("view")))
      Array(view["boards"]).flat_map do |board|
        Array(board["reference_panels"]).map do |panel|
          asset = panel.fetch("asset")
          unless REFERENCE_PANEL_ASSET.match?(asset)
            raise Error, "reference panel asset is outside the public image allowlist: #{asset}"
          end
          asset
        end
      end
    end.uniq.sort
  end

  def public_files(selected_source_set_ids = source_set_ids)
    (
      ROOT_ASSETS + RENDERER_ASSETS + compiled_assets(selected_source_set_ids) +
      reference_panel_assets(selected_source_set_ids)
    ).uniq.sort
  end

  def build!(output: DEFAULT_OUTPUT, validate: true, source_sets: nil)
    selected_source_set_ids = resolve_source_set_ids(source_sets)
    filtered = !source_sets.nil? && !source_sets.empty?
    output = File.expand_path(output)
    validate_output_target!(output)

    stage = File.join(File.dirname(output), ".#{File.basename(output)}-stage-#{Process.pid}")
    FileUtils.rm_rf(stage)
    FileUtils.mkdir_p(stage)

    (ROOT_ASSETS + RENDERER_ASSETS).uniq.each { |path| copy_public_file(path, stage) }
    reference_panel_assets(selected_source_set_ids).each { |path| copy_public_file(path, stage) }
    GENERATED_ASSETS.each { |path, content| write_generated_file(path, content, stage) }
    compile_manifests!(selected_source_set_ids, stage, filtered: filtered)
    verify_sources!(selected_source_set_ids) if validate
    check_compiled_manifests!(selected_source_set_ids, stage, filtered: filtered) if validate
    version_browser_dependencies!(stage, public_build_id(stage))

    file_count = output_files(stage).length
    replace_output!(stage, output)
    File.write(output_marker(output), "generated by scripts/build_pages.rb\n")
    selection = filtered ? "; source sets: #{selected_source_set_ids.join(', ')}" : ""
    puts "Pages output: #{Pathname.new(output).relative_path_from(Pathname.new(ROOT))} (#{file_count} files#{selection})"
    output
  ensure
    FileUtils.rm_rf(stage) if stage && File.exist?(stage)
  end

  def compile_manifests!(selected_source_set_ids, stage, filtered:)
    output_dir = File.join(stage, "renderer/architecture")
    command = [RbConfig.ruby, "renderer/architecture/build-manifest.rb", "--output-dir", output_dir]
    selected_source_set_ids.each { |id| command.concat(["--source-set", id]) } if filtered
    run!(*command)
  end

  def check_compiled_manifests!(selected_source_set_ids, stage, filtered:)
    output_dir = File.join(stage, "renderer/architecture")
    command = [
      RbConfig.ruby,
      "renderer/architecture/build-manifest.rb",
      "--check",
      "--output-dir",
      output_dir,
    ]
    selected_source_set_ids.each { |id| command.concat(["--source-set", id]) } if filtered
    run!(*command)
  end

  def verify_sources!(selected_source_set_ids)
    verifier = ArchitectureVerifier::Verifier.new(root: ROOT)
    selected_source_set_ids.each do |id|
      report = verifier.verify(source_set_id: id, include_manifest: false)
      puts report.to_text
      raise Error, "architecture verification failed for #{id}" unless report.status == "passed"
    end
  end

  def run!(*command)
    return if system(*command, chdir: ROOT)

    raise Error, "command failed: #{command.join(' ')}"
  end

  def validate_output_target!(output)
    root = File.expand_path(ROOT)
    raise Error, "refusing to use the repository root as Pages output" if output == root
    raise Error, "refusing to use the filesystem root as Pages output" if output == File::SEPARATOR
    raise Error, "refusing to replace a symlinked Pages output" if File.symlink?(output)
    return unless File.exist?(output)
    return if Dir.exist?(output) && Dir.empty?(output)
    return if File.file?(output_marker(output))
    return if File.file?(File.join(output, LEGACY_OUTPUT_MARKER))

    raise Error, "refusing to replace non-generated output at #{output}"
  end

  def copy_public_file(path, stage)
    source = File.join(ROOT, path)
    raise Error, "missing public asset: #{path}" unless File.file?(source)

    destination = File.join(stage, path)
    FileUtils.mkdir_p(File.dirname(destination))
    FileUtils.cp(source, destination)
  end

  def public_build_id(stage)
    digest = Digest::SHA256.new
    output_files(stage).each do |path|
      digest << path << "\0" << File.binread(File.join(stage, path)) << "\0"
    end
    digest.hexdigest[0, 12]
  end

  def output_files(root)
    Dir.glob(File.join(root, "**", "*"), File::FNM_DOTMATCH)
      .select { |path| File.file?(path) }
      .map { |path| path.delete_prefix("#{root}/") }
      .sort
  end

  # Safari can retain individual ES modules longer than their importing page,
  # producing a mixed old/new graph after a deployment. A shared content
  # fingerprint makes every local dependency in one build a distinct URL.
  # The source tree stays readable; only the deployable stage is rewritten.
  def version_browser_dependencies!(stage, build_id)
    Dir.glob(File.join(stage, "**", "*.{html,js,mjs}")) do |path|
      source = File.binread(path)
      versioned = if path.end_with?(".html")
        version_html_dependencies(source, build_id)
      else
        version_javascript_dependencies(source, build_id)
      end
      File.binwrite(path, versioned) if versioned != source
    end
  end

  def version_html_dependencies(source, build_id)
    source.gsub(/((?:src|href)=["'])(?!https?:|\/\/|data:)([^"'?#]+\.(?:css|m?js))(["'])/i) do
      "#{Regexp.last_match(1)}#{Regexp.last_match(2)}?v=#{build_id}#{Regexp.last_match(3)}"
    end
  end

  def version_javascript_dependencies(source, build_id)
    source
      .gsub(/((?:from\s+|import\s*)["'])(\.[^"'?#]+\.m?js)(["'])/) do
        "#{Regexp.last_match(1)}#{Regexp.last_match(2)}?v=#{build_id}#{Regexp.last_match(3)}"
      end
      .gsub(/(import\(`\.[^`?]+)(`\))/) do
        "#{Regexp.last_match(1)}?v=#{build_id}#{Regexp.last_match(2)}"
      end
  end

  def output_marker(output)
    File.join(File.dirname(output), ".#{File.basename(output)}#{OUTPUT_MARKER_SUFFIX}")
  end

  def write_generated_file(path, content, stage)
    destination = File.join(stage, path)
    FileUtils.mkdir_p(File.dirname(destination))
    File.write(destination, content)
  end

  def replace_output!(stage, output)
    FileUtils.rm_rf(output) if File.exist?(output)
    FileUtils.mv(stage, output)
  end
end

if $PROGRAM_NAME == __FILE__
  options = { output: PagesBuild::DEFAULT_OUTPUT, source_sets: [] }
  parser = OptionParser.new do |opts|
    opts.banner = "Usage: ruby scripts/build_pages.rb [options]"
    opts.on("--source-set ID", "Publish only this registered source set; repeatable") do |value|
      options[:source_sets] << value
    end
    opts.on("--output PATH", "Build output directory (default: dist)") do |value|
      options[:output] = File.expand_path(value)
    end
    opts.on("-h", "--help", "Show this help") do
      puts opts
      exit 0
    end
  end
  begin
    parser.parse!(ARGV)
    raise OptionParser::InvalidArgument, "unexpected arguments: #{ARGV.join(' ')}" unless ARGV.empty?
    PagesBuild.build!(
      output: options.fetch(:output),
      source_sets: options.fetch(:source_sets).empty? ? nil : options.fetch(:source_sets),
    )
  rescue OptionParser::ParseError, PagesBuild::Error => e
    warn "#{e.message}\n#{parser}"
    exit 2
  end
end
